[package]
name = "l2-executor-methods-fibonacci"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[workspace]
# Empty workspace table to prevent inheriting from parent

[dependencies]
risc0-zkvm = { version = "1.0", default-features = false }

[lib]
crate-type = ["cdylib", "rlib"]
